version: '3.9'

services:
  db:
    image: postgres
    ports:
      - '5433'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      
    ports:
      - "8000:8000"
    depends_on:
      - db
